# Generated by Django 5.2.8 on 2026-03-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem_product_name_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default='old user', max_length=150),
            preserve_default=False,
        ),
    ]
